docs:
	terraform-docs markdown table --output-file README.md --output-mode inject .
	terraform-docs markdown table --output-file README.md --output-mode inject ./vcn

install:
	brew install terraform-docs
