name: link-check
on:
  pull_request:
  push:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: src/
          use-quiet-mode: yes
          use-verbose-mode: no
          config-file: link-check.json
