name: spell-check
on:
  pull_request:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      # https://github.com/streetsidesoftware/cspell-action
      - uses: streetsidesoftware/cspell-action@v6
        with:
          incremental_files_only: true
          config: '.'