name: spell-check
on:
  pull_request:
  push:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: "14"
      - run: npm install -g cspell
      - run: cspell --config ./cspell.json 
